push:
  branches:
    - '*'
pull_request:
  branches:
    - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run tests in Gradle
        run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
#      - uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: test-report
#          path: build/reports/