name: Run tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run tests in Gradle
        run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: build/reports/