name: Run tests
on: [push]

jobs:
  run-tests-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
#      - name: Run tests in Gradle

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
            arguments: test
#        run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
#      - uses: actions/upload-artifact@v3
#        if: failure()
#        with:
#          name: test-report
#          path: build/reports/